name: Update to README

on:
  push:
    branches: [ "master" ]

jobs:
  change-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Insert project tree
        uses: smoothbear/project-tree-action@main
        with:
          email: to be committed email
          username: to be committed username
          token: ${{ secrets.GITHUB_TOKEN }}
